- name: Install Dependencies
        run: |
          pip install playwright playwright-stealth pyotp requests
          playwright install chromium

      - name: Run Login Script
        run: python login_script.py
        env:
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_PASSWORD: ${{ secrets.GH_PASSWORD }}
          GH_2FA_SECRET: ${{ secrets.GH_2FA_SECRET }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}  # 确保在仓库 Secrets 里添加了这个变量
